# Generated by Django 4.1.5 on 2023-01-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_report_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="image",
            new_name="image_path",
        ),
    ]
