# Generated by Django 4.1.5 on 2023-01-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_rename_image_report_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="district",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
