# Generated by Django 4.1.5 on 2023-01-21 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_report_city_report_description_report_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="resolved",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="total_detections",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
